# Model A Configuration
MODEL_NAME: "multilingual_hazard_detector"
VERSION: "1.0.0"

# API Configuration
API:
  HOST: "0.0.0.0"
  PORT: 8000
  DEBUG: true

# Database Configuration
DATABASE:
  MONGODB_URL: "mongodb://localhost:27017"
  DATABASE_NAME: "ocean_hazard_platform"
  COLLECTIONS:
    REPORTS: "hazard_reports"
    ALERTS: "alerts"
    FEEDBACK: "operator_feedback"
    ANOMALIES: "anomalies"

# Model Configurations
MODELS:
  MULTILINGUAL_LLM:
    NAME: "microsoft/DialoGPT-medium"
    MAX_LENGTH: 512
    BATCH_SIZE: 16
    
  NER_MODEL:
    NAME: "ai4bharat/indic-bert"
    LOCATION_ENTITIES: ["LOC", "GPE", "FACILITY"]
    
  SENTIMENT_MODEL:
    NAME: "cardiffnlp/twitter-roberta-base-sentiment-latest"
    
  CLASSIFICATION_MODEL:
    NAME: "xlm-roberta-base"
    LABELS: ["tsunami", "flood", "storm_surge", "high_waves", "coastal_erosion", "other"]

# Language Support
LANGUAGES:
  SUPPORTED: ["en", "hi", "ta", "te", "ml", "kn", "gu", "mr", "bn", "or"]
  DEFAULT: "en"

# Data Sources
DATA_SOURCES:
  SOCIAL_MEDIA:
    TWITTER:
      API_KEY: "your_twitter_api_key"
      API_SECRET: "your_twitter_api_secret"
      ACCESS_TOKEN: "your_twitter_access_token"
      ACCESS_SECRET: "your_twitter_access_secret"
    FACEBOOK:
      ACCESS_TOKEN: "your_facebook_access_token"
    YOUTUBE:
      API_KEY: "your_youtube_api_key"
      
  GOVERNMENT_ALERTS:
    INCOIS_URL: "https://incois.gov.in/portal/alerts"
    POLLING_INTERVAL: 300  # seconds
    
# Anomaly Detection
ANOMALY_DETECTION:
  WINDOW_SIZE: 3600  # 1 hour in seconds
  THRESHOLD_MULTIPLIER: 2.5
  MIN_REPORTS_FOR_ANOMALY: 5

# Geolocation
GEOLOCATION:
  FUZZY_MATCH_THRESHOLD: 80
  MAX_DISTANCE_KM: 50
  NOMINATIM_USER_AGENT: "ocean_hazard_platform"

# Logging
LOGGING:
  LEVEL: "INFO"
  FORMAT: "{time} | {level} | {message}"
  FILE: "logs/model_a.log"
  ROTATION: "1 day"